### ISSUE TITLE
Add note when deploying apps

### ISSUE THREAD

**Issue by damian-rzeszot** [dag-io/appetize-deploy-step#1]
It would be nice to add note to each deployed app.
There is information that is possible (in docs).

**Comment by dagio** [comment]
Sure, it sounds great. I will add a field. Maybe we should give it a default value. The git commit message could be nice ?

**Comment by BirmacherAkos** [comment]
Hi!

We have moved this step to https://github.com/bitrise-steplib/steps-appetize-io-deploy repository. It has been rewritten in Golang.
