### ISSUE TITLE
Is this step abandoned?

### ISSUE THREAD

**Issue by viktorbenei** [dag-io/appetize-deploy-step#3]
Based on https://discuss.bitrise.io/t/integrate-with-https-appetize-io/114/24?u=viktorbenei it is

If it's indeed deprecated, would you mind if we'd transfer it into the Bitrise Community github organization? https://github.com/bitrise-community/

**Comment by BirmacherAkos** [comment]
Hi!

We have moved this step to https://github.com/bitrise-steplib/steps-appetize-io-deploy repository. It has been rewritten in Golang.
